// ============================================================
//  bram.sv  —  Synthesizable Block RAM (Xilinx BRAM inference)
//
//  Dual-port True BRAM:
//    Port A = Instruction fetch (read-only, 32-bit word aligned)
//    Port B = Data load/store   (read/write, byte-enable)
//
//  SIZE_BYTES: Total memory size in bytes (default 64KB)
//              This fits comfortably in the Arty S7-50's BRAM.
//
//  Initialization:
//    Set INIT_FILE to a .hex file path to preload firmware.
//    The .hex file is generated by the RISC-V GCC toolchain.
//
//  Xilinx BRAM inference guidelines followed:
//    - Synchronous read (registered output)
//    - Byte-enable write (for SB/SH/SW support)
//    - No reset on read outputs (BRAM doesn't support it)
// ============================================================
`timescale 1ns/1ps

module bram #(
    parameter int    SIZE_BYTES = 65536,          // 64 KB default
    parameter string INIT_FILE  = ""              // .hex firmware file
) (
    input  logic        clk,

    // ---- Port A: Instruction Fetch (Read Only) ----
    input  logic [31:0] a_addr,     // Byte address
    output logic [31:0] a_rdata,    // 32-bit instruction word

    // ---- Port B: Data Load/Store (Read/Write) ----
    input  logic [31:0] b_addr,     // Byte address
    input  logic [31:0] b_wdata,    // Write data
    input  logic [3:0]  b_we,       // Byte-enables (1 bit per byte)
    input  logic        b_re,       // Read enable
    output logic [31:0] b_rdata     // Read data
);

    localparam int WORDS = SIZE_BYTES / 4;  // Number of 32-bit words

    // The actual memory array (Xilinx tools will infer BRAM)
    logic [31:0] mem [0:WORDS-1];

    // -------------------------------------------------------
    //  Memory initialization from firmware .hex file
    // -------------------------------------------------------
    initial begin
        integer i;
        // Fill with NOP (ADDI x0, x0, 0) by default
        for (i = 0; i < WORDS; i = i + 1)
            mem[i] = 32'h0000_0013;
        // Load firmware if provided
        if (INIT_FILE != "")
            $readmemh(INIT_FILE, mem);
    end

    // -------------------------------------------------------
    //  Port A — Instruction Fetch (synchronous, read-only)
    //  Word-aligned access: addr[1:0] ignored
    // -------------------------------------------------------
    always_ff @(posedge clk) begin
        a_rdata <= mem[a_addr[$clog2(WORDS)+1:2]];
    end

    // -------------------------------------------------------
    //  Port B — Data Memory (synchronous read/write)
    //  Byte-enables allow SB/SH/SW at any alignment
    // -------------------------------------------------------
    always_ff @(posedge clk) begin
        // Write with byte enables
        if (b_we[0]) mem[b_addr[$clog2(WORDS)+1:2]][7:0]   <= b_wdata[7:0];
        if (b_we[1]) mem[b_addr[$clog2(WORDS)+1:2]][15:8]  <= b_wdata[15:8];
        if (b_we[2]) mem[b_addr[$clog2(WORDS)+1:2]][23:16] <= b_wdata[23:16];
        if (b_we[3]) mem[b_addr[$clog2(WORDS)+1:2]][31:24] <= b_wdata[31:24];

        // Read (registered output — standard BRAM behavior)
        if (b_re)
            b_rdata <= mem[b_addr[$clog2(WORDS)+1:2]];
    end

endmodule
