// ============================================================
//  soc_top.sv  —  RV32 SoC Top-Level for Arty S7-50
//
//  This module integrates:
//    1. cpu_top   — Our RV32I 5-stage pipelined processor
//    2. bram      — 64KB unified BRAM (instruction + data)
//    3. uart      — Memory-mapped UART peripheral (115200 baud)
//    4. bus_mux   — Address decoder routing CPU to peripherals
//
//  ===================================================
//  Memory Map (Physical Address Space)
//  ===================================================
//    0x0000_0000 – 0x0000_FFFF  : Instruction BRAM (64KB)
//    0x2000_0000 – 0x2000_FFFF  : Data BRAM (64KB)
//    0x1000_0000 – 0x1000_000B  : UART Registers
//       +0x0: TX Write (write byte → sends over UART)
//       +0x4: RX Read  (read byte ← received from PC)
//       +0x8: Status   (bit0=TX_READY, bit1=RX_VALID)
//
//  ===================================================
//  On-chip resources used (Arty S7-50):
//    BRAM: 2× RAMB36 blocks (64KB total)
//    LUTs: ~2000-4000 estimated (mainly CPU datapath)
//    FFs:  ~1500-3000 (pipeline registers)
//  ===================================================
//
//  Board: Xilinx Arty S7-50 (XC7S50-CSGA324)
//  Clock: 12 MHz on-board (we use Xilinx MMCM to gen 100 MHz)
// ============================================================
`timescale 1ns/1ps

module soc_top (
    // ---- Board Pins ----
    input  logic        clk_12mhz,    // Arty S7 on-board 12 MHz oscillator
    input  logic        rst_btn,      // Active-high reset button (BTN0)

    // ---- UART Pins (USB-UART via onboard FTDI) ----
    output logic        uart_txd_in,  // FPGA TX → PC RX (V12 on Rev E)
    input  logic        uart_rxd_out, // PC TX → FPGA RX (R12 on Rev E)

    // ---- Status LEDs ----
    output logic [3:0]  led           // LED[0]=run, LED[1]=PLL locked
);

    // -------------------------------------------------------
    //  PLL / MMCM: Generate 100 MHz from 12 MHz board clock
    //  This is instantiated as a Xilinx primitive.
    //  In simulation, clk_100mhz is driven directly.
    // -------------------------------------------------------
    logic clk_100mhz;
    logic pll_locked;

`ifdef SYNTHESIS
    // Xilinx MMCM primitive (generated by Clocking Wizard IP)
    clk_wiz_0 u_pll (
        .clk_in1 (clk_12mhz),
        .clk_out1(clk_100mhz),
        .locked  (pll_locked),
        .reset   (1'b0)
    );
`else
    // Simulation: pass through directly (no PLL needed)
    assign clk_100mhz = clk_12mhz;
    assign pll_locked  = 1'b1;
`endif

    // -------------------------------------------------------
    //  Reset synchronizer
    //  The Arty S7 buttons are Active-High (1 when pressed).
    //  We invert it here to get an active-low reset signal.
    // -------------------------------------------------------
    logic [3:0] rst_sync_cnt;
    logic       rst_n;
    logic       rst_btn_n;

    assign rst_btn_n = !rst_btn;

    always_ff @(posedge clk_100mhz or negedge rst_btn_n) begin
        if (!rst_btn_n) begin
            rst_sync_cnt <= '0;
            rst_n        <= 1'b0;
        end else if (!pll_locked) begin
            rst_sync_cnt <= '0;
            rst_n        <= 1'b0;
        end else if (!rst_n) begin
            if (rst_sync_cnt == 4'hF)
                rst_n <= 1'b1;
            else
                rst_sync_cnt <= rst_sync_cnt + 1;
        end
    end

    // -------------------------------------------------------
    //  CPU signals
    // -------------------------------------------------------
    logic [31:0] dbg_pc, dbg_instr, dbg_alu_result, dbg_reg_rd_data;

    // -------------------------------------------------------
    //  Internal bus signals
    //  Our cpu_top connects to memory through the memory.sv
    //  internal logic. We need to expose the data bus externally
    //  via a simplified interface using the debug/mem ports.
    //
    //  NOTE: We insert a "memory adapter" layer to bridge
    //  the cpu_top's internal memory interface to our SoC BRAM
    //  and UART. The cpu_top's internal memory.sv is replaced
    //  by the SoC memory system via parameters.
    // -------------------------------------------------------

    // -------------------------------------------------------
    //  Instruction BRAM (Port A = fetch, read-only)
    // -------------------------------------------------------
    logic [31:0] imem_addr;
    logic [31:0] imem_rdata;

    // -------------------------------------------------------
    //  Data bus (from CPU to bus fabric)
    // -------------------------------------------------------
    logic [31:0] dmem_addr;
    logic [31:0] dmem_wdata;
    logic [31:0] dmem_rdata;
    logic        dmem_rd_en;
    logic        dmem_wr_en;
    logic [3:0]  dmem_we;      // Byte enables for store instructions
    logic [2:0]  dmem_funct3;  // From CPU MEM stage

    // -------------------------------------------------------
    //  Address Decoder (Bus Fabric)
    //  Routes data bus to correct peripheral
    // -------------------------------------------------------
    localparam logic [31:0] BRAM_BASE  = 32'h2000_0000;
    localparam logic [31:0] BRAM_MASK  = 32'h0000_FFFF;  // 64KB
    localparam logic [31:0] UART_BASE  = 32'h1000_0000;
    localparam logic [31:0] UART_MASK  = 32'h0000_000F;  // 16 bytes

    logic sel_bram, sel_uart;
    assign sel_bram = ((dmem_addr & ~BRAM_MASK) == BRAM_BASE);
    assign sel_uart = ((dmem_addr & ~UART_MASK) == UART_BASE);

    // -------------------------------------------------------
    //  Read data mux back to CPU
    // -------------------------------------------------------
    logic [31:0] bram_rdata;
    logic [31:0] uart_rdata;

    always_comb begin
        dmem_rdata = 32'h0;
        if (sel_bram) dmem_rdata = bram_rdata;
        if (sel_uart) dmem_rdata = uart_rdata;
    end

    // -------------------------------------------------------
    //  Byte-enable generation from funct3
    // -------------------------------------------------------
    always_comb begin
        case (dmem_funct3)
            3'b000: begin // SB - store byte
                case (dmem_addr[1:0])
                    2'b00: dmem_we = 4'b0001;
                    2'b01: dmem_we = 4'b0010;
                    2'b10: dmem_we = 4'b0100;
                    2'b11: dmem_we = 4'b1000;
                    default: dmem_we = 4'b0000;
                endcase
            end
            3'b001: begin // SH - store halfword
                dmem_we = dmem_addr[1] ? 4'b1100 : 4'b0011;
            end
            default: dmem_we = dmem_wr_en ? 4'b1111 : 4'b0000; // SW
        endcase
        if (!dmem_wr_en) dmem_we = 4'b0000;
    end

    // -------------------------------------------------------
    //  Unified 64KB BRAM
    //  Port A: CPU instruction fetch
    //  Port B: CPU data load/store
    // -------------------------------------------------------
    bram #(
        .SIZE_BYTES(65536),
        .INIT_FILE ("firmware.vmem")  // Generated by 'make program' in software/
    ) u_bram (
        .clk    (clk_100mhz),
        // Port A — instruction fetch
        .a_addr (imem_addr),
        .a_rdata(imem_rdata),
        // Port B — data access
        .b_addr (dmem_addr),
        .b_wdata(dmem_wdata),
        .b_we   (sel_bram ? dmem_we : 4'b0),
        .b_re   (sel_bram & dmem_rd_en),
        .b_rdata(bram_rdata)
    );

    // -------------------------------------------------------
    //  UART Peripheral
    // -------------------------------------------------------
    uart #(
        .CLK_FREQ (100_000_000),
        .BAUD_RATE(115_200)
    ) u_uart (
        .clk        (clk_100mhz),
        .rst_n      (rst_n),
        .addr       (dmem_addr[3:0]),
        .wr_data    (dmem_wdata),
        .wr_en      (sel_uart & dmem_wr_en),
        .rd_en      (sel_uart & dmem_rd_en),
        .rd_data    (uart_rdata),
        .uart_tx_pin(uart_txd_in),
        .uart_rx_pin(uart_rxd_out)
    );

    // -------------------------------------------------------
    //  CPU Instantiation
    //  NOTE: cpu_top uses its internal memory.sv by default.
    //  We create a "soc_cpu_top.sv" wrapper that replaces the
    //  internal memory with our external BRAM bus connections.
    //  (This is in Step 2 of Phase 8 - the SoC CPU wrapper)
    // -------------------------------------------------------
    cpu_top_soc #(
        .XLEN(32)
    ) u_cpu (
        .clk            (clk_100mhz),
        .rst_n          (rst_n),
        .ext_interrupt  (1'b0),

        // Instruction bus (→ BRAM Port A)
        .imem_addr      (imem_addr),
        .imem_rdata     (imem_rdata),

        // Data bus (→ Address decoder → BRAM/UART)
        .dmem_addr      (dmem_addr),
        .dmem_wdata     (dmem_wdata),
        .dmem_rdata     (dmem_rdata),
        .dmem_rd_en     (dmem_rd_en),
        .dmem_wr_en     (dmem_wr_en),
        .dmem_funct3    (dmem_funct3),

        // Debug
        .dbg_pc         (dbg_pc),
        .dbg_instr      (dbg_instr),
        .dbg_alu_result (dbg_alu_result),
        .dbg_reg_rd_data(dbg_reg_rd_data)
    );

    // -------------------------------------------------------
    //  Status LEDs
    // -------------------------------------------------------
    assign led[0] = rst_n;          // Solid on = CPU running
    assign led[1] = pll_locked;     // Solid on = PLL locked
    assign led[2] = 1'b0;
    assign led[3] = 1'b0;

endmodule
